name: hermes-bo-deploy 

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        make run
        make start
    - name: Run unit tests
      run: |
        make test
    - name: Setup env variables
      run: |
          echo 'SCP_FILES=scraper/github/build.tar' >> $GITHUB_ENV
          echo 'ARCHIVE=build.tar' >> $GITHUB_ENV
          echo 'SCP_TARGET<<EOF' >> $GITHUB_ENV
          cat ./deploy/target.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          tar -cvf build.tar $(find ./* -maxdepth 0 | grep -vf ./deploy/excluded_files.txt)
    - name: Copy file via scp
      uses: appleboy/scp-action@master
      with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_DEPLOY_USERNAME }}
          key: ${{ secrets.DROPLET_DEPLOY_SSHKEY }}
          source: ${{ env.SCP_FILES }}
          target: ${{ env.SCP_TARGET }}
          overwrite: true
    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_DEPLOY_USERNAME }}
          key: ${{ secrets.DROPLET_DEPLOY_SSHKEY }}
          script: cd ${{ env.SCP_TARGET }}/scraper/github && tar -xvf ${{ env.ARCHIVE }} && rm -rf ${{ env.ARCHIVE }}
       
